"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class rn_packet_t(object):
    __slots__ = ["timestamp", "cmd_n_err", "exp_n_rslt"]

    def __init__(self):
        self.timestamp = 0
        self.cmd_n_err = 0
        self.exp_n_rslt = ""

    def encode(self):
        buf = BytesIO()
        buf.write(rn_packet_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.cmd_n_err))
        __exp_n_rslt_encoded = self.exp_n_rslt.encode('utf-8')
        buf.write(struct.pack('>I', len(__exp_n_rslt_encoded)+1))
        buf.write(__exp_n_rslt_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rn_packet_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rn_packet_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = rn_packet_t()
        self.timestamp, self.cmd_n_err = struct.unpack(">qi", buf.read(12))
        __exp_n_rslt_len = struct.unpack('>I', buf.read(4))[0]
        self.exp_n_rslt = buf.read(__exp_n_rslt_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if rn_packet_t in parents: return 0
        tmphash = (0xc2972e89b7626735) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if rn_packet_t._packed_fingerprint is None:
            rn_packet_t._packed_fingerprint = struct.pack(">Q", rn_packet_t._get_hash_recursive([]))
        return rn_packet_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

